// osdm-demo-app-angular/src/app/landing/landing.component.ts
import { CUSTOM_ELEMENTS_SCHEMA, Component } from '@angular/core';
import { Router } from '@angular/router';
import OSDM from 'osdm-client-lib';
import '@sbb-esta/lyne-elements/button.js';
import '@sbb-esta/lyne-elements/form-field.js';
import { FormsModule } from '@angular/forms';
import { baseUrl } from '../../enviroment';

const passengers = [
  {
    externalRef: 'passenger_1',
    dateOfBirth: '1980-01-01',
    type: 'PERSON',
    detail: {
      firstName: 'Elo',
      lastName: 'Musterperson',
      phoneNumber: '+49475000001',
      email: 'elo.musterperson@dlh.com',
    },
  },
];

@Component({
  selector: 'app-landing',
  standalone: true,
  imports: [FormsModule],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  templateUrl: './landing.component.html',
  styleUrl: './landing.component.css',
})
export class LandingComponent {
  constructor(private router: Router) {}
  origin = '';
  destination = '';

  offerResults: any = [];
  tripResults: any = [];

  getOffers() {
    OSDM.searchOffers(
      baseUrl,
      {
        stopPlaceRef: this.origin,
        objectType: 'StopPlaceRef',
      },
      {
        stopPlaceRef: this.destination,
        objectType: 'StopPlaceRef',
      },
      passengers,
      '2024-10-10T10:00:00Z'
    ).then((offers: any) => {
      console.log(offers);
      this.offerResults = offers.offers;
      this.tripResults = offers.trips;
    });
  }

  buyOffer(offerId: any) {
    // Makes a booking and navigates to an overview screen
    OSDM.createBooking(baseUrl, offerId, passengers).then((booking: any) => {
      const bookingId = booking.booking.id;
      OSDM.fulfillBooking(baseUrl, bookingId).then(() => {
        this.router.navigate(['/booking'], { queryParams: { b: bookingId } });
      });
    });
  }
}

<div class="flex flex-col">
  <div
    class="flex flex-col md:flex-row gap-5 items-center w-full p-10 justify-center"
  >
    <sbb-form-field data-testid="form-field">
      <label>Origin</label>
      <input
        (keyup)="doUpdate(origin)"
        (focusout)="doUpdate(origin)"
        (mouseup)="doUpdate(origin)"
        [(ngModel)]="origin"
      />
      <sbb-autocomplete>
        @for (station of stations; track station) {
        <sbb-option value="{{ station }}">{{ station }}</sbb-option>
        }
      </sbb-autocomplete>
    </sbb-form-field>
    <sbb-form-field>
      <label>Destination</label>
      <input
        (keyup)="doUpdate(destination)"
        (focusout)="doUpdate(destination)"
        (mouseup)="doUpdate(destination)"
        type="text"
        placeholder="Input placeholder"
        [(ngModel)]="destination"
      />
      <sbb-autocomplete>
        @for (station of stations; track station) {
        <sbb-option value="{{ station }}">{{ station }}</sbb-option>
        }
      </sbb-autocomplete>
    </sbb-form-field>
    <sbb-form-field>
      <label>Via</label>
      <input
        (keyup)="doUpdate(via)"
        (focusout)="doUpdate(via)"
        (mouseup)="doUpdate(via)"
        type="text"
        placeholder="Input placeholder"
        [(ngModel)]="via"
      />
      <sbb-autocomplete>
        @for (station of stations; track station) {
        <sbb-option value="{{ station }}">{{ station }}</sbb-option>
        }
      </sbb-autocomplete>
    </sbb-form-field>
    <sbb-button (click)="getOffers()" [disabled]="loading">
      @if (loading) {
      <sbb-loading-indicator variant="circle" size="s"></sbb-loading-indicator>
      } Search
    </sbb-button>
  </div>
  @if (showEasterEgg) {
  <div class="image-container">
    <img
      [ngSrc]="imageSrc"
      height="766"
      width="1008"
      alt="image"
      (click)="updateImage()"
    />
  </div>
  }
  <div class="flex flex-col md:flex-row justify-center gap-5 p-10">
    <div class="w-full md:w-1/2">
      @for (trip of tripResults; track trip?.id) {
      <sbb-card type="submit" size="m" color="white">
        <sbb-card-button
          (click)="selectTrip(trip)"
          [active]="selectedTrip === trip.id"
          >Select
        </sbb-card-button>

        <div>
          <strong>Duration:</strong> {{ trip.duration | duration }}<br />
          <strong>Transfers:</strong> {{ trip.transfers }}<br />
        </div>

        <div class="flex w-full">
          <strong>{{ pearlDepartureMap.get(trip.id) | date : "HH:mm" }}</strong>
          <sbb-pearl-chain-time
            class="flex-1"
            [legs]="pearlMap.get(trip.id)"
          ></sbb-pearl-chain-time>
          <strong>{{ pearlArrivalMap.get(trip.id) | date : "HH:mm" }}</strong>
        </div>
        <!--                    <span>{{trip.legs[0].timedLeg.start.serviceDeparture.timetabledTime}}</span>-->
        <!--                    [arrival-time]="trip.legs[0].timedLeg.start.serviceDeparture.timetabledTime"-->
        <!--                      departure-time="2022-12-11T12:11:00"-->
      </sbb-card>
      }
    </div>
    @if (selectedOffers) {
    <div class="w-full md:w-1/2">
      <app-offers [offers]="selectedOffers"></app-offers>
    </div>
    }
  </div>
</div>

// osdm-demo-app-react/src/pages/Landing.js
import { SbbButton } from "@sbb-esta/lyne-react/button";
import {
  SbbFormField,
  SbbFormFieldClear,
} from "@sbb-esta/lyne-react/form-field";
import { SbbCard } from "@sbb-esta/lyne-react/card";
import OSDM from "osdm-client-lib";
import { useState } from "react";
import { useNavigate } from "react-router-dom";

const passengers = [
  {
    externalRef: "passenger_1",
    dateOfBirth: "1980-01-01",
    type: "PERSON",
    detail: {
      firstName: "Elo",
      lastName: "Musterperson",
      phoneNumber: "+49475000001",
      email: "elo.musterperson@dlh.com",
    },
  },
];

const Landing = () => {
  const [origin, setOrigin] = useState([]);
  const [destination, setDestination] = useState([]);
  const [tripResults, setTripResults] = useState([]);
  const [offerResults, setOfferResults] = useState([]);
  const navigate = useNavigate();

  const getOffers = () => {
    OSDM.searchOffers(
      {
        stopPlaceRef: origin,
        objectType: "StopPlaceRef",
      },
      {
        stopPlaceRef: destination,
        objectType: "StopPlaceRef",
      },
      passengers,
      "2024-10-10T10:00:00Z"
    ).then((offers) => {
      console.log(offers);
      setOfferResults(offers.offers);
      setTripResults(offers.trips);
    });
  };

  const buyOffer = (offerId) => {
    // Makes a booking and navigates to an overview screen
    OSDM.createBooking(offerId, passengers).then((booking) => {
      const bookingId = booking.booking.id;
      OSDM.fulfillBooking(bookingId).then(() => {
        navigate("/booking", { state: { bookingId } });
      });
    });
  };

  return (
    <div className="flex flex-col">
      <div className="flex gap-5 items-center w-full p-10 justify-center">
        <SbbFormField>
          <label>Origin</label>
          <input
            type="text"
            placeholder="Input placeholder"
            value={origin}
            onChange={(e) => setOrigin(e.target.value)}
          />
          <SbbFormFieldClear></SbbFormFieldClear>
        </SbbFormField>
        <SbbFormField>
          <label>Destination</label>
          <input
            type="text"
            placeholder="Input placeholder"
            value={destination}
            onChange={(e) => setDestination(e.target.value)}
          />
          <SbbFormFieldClear></SbbFormFieldClear>
        </SbbFormField>
        <SbbButton onClick={getOffers}>Search</SbbButton>
      </div>
      <div className="flex flex-col">
        {tripResults.map((trip) => (
          <SbbCard type="submit" form="buy" value="trip" key={trip.id}>
            {trip.startTime}
            <div className="flex flex-col">
              {offerResults
                .filter((offer) => offer.tripCoverage.coveredTripId === trip.id)
                .map((offer) => (
                  <sbb-option
                    value="Value 1"
                    icon-name="ticket"
                    key={offer.offerId}
                  >
                    {offer.offerSummary.minimalPrice.amount}

                    <SbbButton onClick={() => buyOffer(offer.offerId)}>
                      Buy
                    </SbbButton>
                  </sbb-option>
                ))}
            </div>
          </SbbCard>
        ))}
      </div>
    </div>
  );
};

export default Landing;
