// osdm-demo-app-react/src/pages/Booking.js
import { SbbButton } from "@sbb-esta/lyne-react/button";
import { useLocation } from "react-router-dom";
import OSDM from "osdm-client-lib";
import { useEffect, useState } from "react";

const Booking = () => {
  const location = useLocation();
  const data = location.state;

  const [ticketData, setTicketData] = useState();

  const fetchFulfillment = () => {
    OSDM.getBooking(data.bookingId)
      .then((booking) => {
        if (!booking.booking?.fulfillments) {
          setTimeout(fetchFulfillment, 2000);
        } else {
          setTicketData(booking);
        }
      })
      .catch(() => {
        setTimeout(fetchFulfillment, 2000);
      });
  };

  useEffect(() => {
    fetchFulfillment();
  }, []);

  const openTicket = () => {
    // ToDo Finish
    if (ticketData && ticketData.booking) {
      window
        .open(
          ticketData.booking.fulfillments[0].fulfillmentDocuments[0]
            .downloadLink,
          "_blank"
        )
        .focus();
    }
  };

  return (
    <div className="flex flex-col w-full justify-center items-center">
      <h1>Booking</h1>
      <span>{JSON.stringify(ticketData)}</span>
      <SbbButton onClick={openTicket}>Open Ticket</SbbButton>
    </div>
  );
};

export default Booking;

// osdm-demo-app-angular/src/app/booking/booking.component.ts
import { CUSTOM_ELEMENTS_SCHEMA, Component } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import OSDM from 'osdm-client-lib';
import '@sbb-esta/lyne-elements/button.js';

@Component({
  selector: 'app-booking',
  standalone: true,
  imports: [],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  templateUrl: './booking.component.html',
  styleUrl: './booking.component.css',
})
export class BookingComponent {
  constructor(private route: ActivatedRoute) {}

  ticketData = {};

  fetchFulfillment(bookingId: any) {
    OSDM.getBooking(bookingId)
      .then((booking: any) => {
        if (!booking.booking?.fulfillments) {
          setTimeout(() => this.fetchFulfillment(bookingId), 2000);
        } else {
          this.ticketData = booking;
        }
      })
      .catch(() => {
        setTimeout(() => this.fetchFulfillment(bookingId), 2000);
      });
  }

  openTicket() {
    (window as any)
      .open(
        (this.ticketData as any).booking.fulfillments[0].fulfillmentDocuments[0]
          .downloadLink,
        '_blank'
      )
      .focus();
  }

  ngOnInit(): void {
    this.fetchFulfillment((this.route.queryParams as any).value.b);
  }
}

<div class="flex flex-col w-full justify-center items-center">
  <h1>Booking</h1>
  <span>Test</span>
  <sbb-button (click)="openTicket()">Open Ticket</sbb-button>
</div>
